### ISSUE TITLE
Leaderboard

### ISSUE THREAD

**Issue by kaisbaccour** [noislabs/nois-oracle-dashboard#5]
Make a leaderboard that shows the 10 bot operators with the highest number of submissions and or the highest amount of incentive received

**Comment by webmaster128** [comment]
Yeah, I think we should track the points and the number of submissions independently for such a view.

**Comment by webmaster128** [comment]
Done, see https://randomness.nois.network/bots

<img width="950" alt="Bildschirm­foto 2023-02-22 um 00 12 08" src="https://user-images.githubusercontent.com/2603011/220479867-60f9fb9d-c38d-40a2-a17a-67092da3a046.png">

The only thing that I see missing is a link to that page.
